const CHANGE_BANNER = "CHANGE_BANNER"
const CHAGE_RECOMMEND = "CHAGE_RECOMMEND"
const FETCH_HOMEMULTIDATA = "FETCH_HOMEMULTIDATA"
export {
    CHAGE_RECOMMEND,
    CHANGE_BANNER,
    FETCH_HOMEMULTIDATA
}