const ADD_NUMBER = "ADD_NUMBER"
const SUB_NUMBER = "SUB-NUMBER"
const CHANGE_BANNER = "CHANGE_BANNER"
const CHAGE_RECOMMEND = "CHAGE_RECOMMEND"
const FETCH_HOMEMULTIDATA = "FETCH_HOMEMULTIDATA"
export {
    ADD_NUMBER,
    SUB_NUMBER,
    CHAGE_RECOMMEND,
    CHANGE_BANNER,
    FETCH_HOMEMULTIDATA
}